# Generated by Django 5.2.6 on 2026-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('chairs', 'Chairs'), ('desks', 'Desks'), ('tables', 'Tables'), ('beds', 'Beds'), ('sofas', 'Sofas'), ('wardrobes', 'Wardrobes'), ('cabinets', 'Cabinets'), ('bookshelves', 'Bookshelves'), ('tv units', 'TV Units'), ('dining sets', 'Dining Sets'), ('office furniture', 'Office Furniture'), ('outdoor furniture', 'Outdoor Furniture')], max_length=50)),
                ('description', models.TextField()),
                ('has_custom_size', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
